// apps/sdk-example-nextjs/pages/_app.tsx
import { AppProps } from 'next/app';
import Head from 'next/head';
import './styles.css';
import { MoneriumProvider } from '@monerium/ui';

function CustomApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Welcome to sdk-example-nextjs!</title>
      </Head>
      <main className="app">
        <MoneriumProvider
          clientId="f99e629b-6dca-11ee-8aa6-5273f65ed05b"
          redirectUrl="http://localhost:5173"
        >
          <Component {...pageProps} />
        </MoneriumProvider>
      </main>
    </>
  );
}

export default CustomApp;

// apps/sdk-example-svelte/src/app/App.svelte
<script lang="ts">
  import { MoneriumClient } from '@monerium/sdk';
  let client = new MoneriumClient({
    clientId: 'f99e629b-6dca-11ee-8aa6-5273f65ed05b',
    redirectUrl: 'http://localhost:4200',
  });

  let authCtx;
  let isAuthorized = true;
  (async () => {
    isAuthorized = await client.connect();
    authCtx = await client.getAuthContext();
    console.log(authCtx);
  })();
</script>

{#if !isAuthorized}
  <button on:click={() => client.authorize()}> Connect </button>
{/if}
<p>{authCtx?.name || authCtx?.email}</p>
