// apps/sdk-example-svelte/src/app/App.svelte
<script lang="ts">
  import { MoneriumClient } from '@monerium/sdk';
  let client = new MoneriumClient({
    clientId: 'f99e629b-6dca-11ee-8aa6-5273f65ed05b',
    redirectUrl: 'http://localhost:4200',
  });

  let authCtx;
  let isAuthorized = true;
  (async () => {
    isAuthorized = await client.connect();
    authCtx = await client.getAuthContext();
    console.log(authCtx);
  })();
</script>

{#if !isAuthorized}
  <button on:click={() => client.authorize()}> Connect </button>
{/if}
<p>{authCtx?.name || authCtx?.email}</p>

// apps/examples/sdk-react/src/app/app.tsx
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import styles from './app.module.css';
import { useEffect, useState } from 'react';
import { MoneriumClient, AuthContext } from '@monerium/sdk';

export function App() {
  const [authCtx, setAuthCtx] = useState<AuthContext | null>(null);
  const [monerium, setMonerium] = useState<MoneriumClient>();
  const [isAuthorized, setIsAuthorized] = useState<boolean>(false);

  useEffect(() => {
    const sdk = new MoneriumClient({
      environment: 'sandbox',
      clientId: 'f99e629b-6dca-11ee-8aa6-5273f65ed05b',
      redirectUrl: 'http://localhost:4200',
    });
    setMonerium(sdk);
  }, []);

  useEffect(() => {
    const connect = async () => {
      if (monerium) {
        setIsAuthorized(await monerium.getAccess());
      }
    };

    connect();

    return () => {
      if (monerium) {
        monerium.disconnect();
      }
    };
  }, [monerium]);

  useEffect(() => {
    const fetchData = async () => {
      if (monerium && isAuthorized) {
        try {
          setAuthCtx(await monerium.getAuthContext());
        } catch (err) {
          console.error('Error fetching data:', err);
        }
      }
    };
    fetchData();
  }, [monerium, isAuthorized]);

  return (
    <div>
      <p>Welcome sdk-example-react</p>
      {!isAuthorized && (
        <button
          onClick={() =>
            monerium?.authorize({
              // address: '0xValidAddress72413Fa92980B889A1eCE84dD',
              // signature: '0x',
              // chainId: 137,
            })
          }
        >
          Connect
        </button>
      )}

      <p>{authCtx?.name || authCtx?.email}</p>
    </div>
  );
}

export default App;
